name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'seamol1701/auction-svc'
            path: 'src/AuctionService'
          - name: 'seamol1701/search-svc'
            path: 'src/SearchService'
          - name: 'seamol1701/bid-svc'
            path: 'src/BidService'
          - name: 'seamol1701/identity-svc'
            path: 'src/IdentityService'
          - name: 'seamol1701/gateway-svc'
            path: 'src/GatewayService'
          - name: 'seamol1701/notify-svc'
            path: 'src/NotificationService'
          - name: 'seamol1701/web-app'
            path: 'frontend/web-app'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{matrix.service.path}}/Dockerfile
        push: true
        tags: ${{matrix.service.name}}:latest
